// frontend/src/routes/dashboard/index.svelte
<script lang="ts">
  import { p } from "sv-router/generated";

  type Project = {
    id: string;
    name: string;
  };

  // TODO: Replace with API
  let projects = $state<Project[]>([
    { id: "1", name: "Project 1" },
    { id: "2", name: "Project 2" },
  ]);

  let newProjectName = $state("");

  function createProject() {
    if (!newProjectName.trim()) {
      return;
    }

    projects.push({ id: crypto.randomUUID(), name: newProjectName.trim() });
    newProjectName = "";
  }

  function deleteProject(id: string) {
    projects = projects.filter((project) => project.id !== id);
  }
</script>

<main>
  <h1>Projects</h1>
  <ul>
    {#each projects as project (project.id)}
      <li>
        <span>{project.name}</span>
        <a href={p("/dashboard")}>Open</a>
        <button onclick={() => deleteProject(project.id)}>Delete</button>
      </li>
    {/each}
  </ul>

  <input value={newProjectName} placeholder="Project name" />
  <button onclick={createProject}>New Project</button>
</main>

// frontend/src/routes/Dashboard.tsx
import { A } from "@solidjs/router";
import { For, createSignal } from "solid-js";
import { createStore, produce } from "solid-js/store";

interface Project {
  id: string;
  name: string;
}

export default function Dashboard() {
  const [projects, setProjects] = createStore<Project[]>([
    { id: "1", name: "Project 1" },
    { id: "2", name: "Project 2" },
  ]);
  const [newName, setNewName] = createSignal("");

  function createProject() {
    const name = newName().trim();
    if (!name) return;
    setProjects(projects.length, { id: crypto.randomUUID(), name });
    setNewName("");
  }

  function deleteProject(id: string) {
    setProjects(
      produce((draft) => {
        const idx = draft.findIndex((p) => p.id === id);
        if (idx !== -1) draft.splice(idx, 1);
      })
    );
  }

  return (
    <main>
      <h1>Projects</h1>
      <ul>
        <For each={projects}>
          {(project) => (
            <li>
              <span>{project.name}</span>
              <A href={`/project/${project.id}`}>Open</A>
              <button
                onClick={() => {
                  deleteProject(project.id);
                }}
              >
                Delete
              </button>
            </li>
          )}
        </For>
      </ul>
      <input
        value={newName()}
        onInput={(e) => setNewName(e.currentTarget.value)}
        placeholder="Project name"
      />
      <button onClick={createProject}>New Project</button>
    </main>
  );
}
